version: "3.7"
services:
  web:
    restart: unless-stopped
    build:
      context: /home/pasha/PycharmProjects/pythonProject/Django_tutorial/first_django/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - django_network
    entrypoint: /bin/sh -c "root/first_django/wait-for-it.sh dbpsql:5432 -- python root/first_django/manage.py makemigrations && python root/first_django/manage.py migrate && python root/first_django/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pgadmin
      - dbpsql

  dbpsql:
    image: postgres:latest
    container_name: postgres13
    env_file:
      - psql.env
    restart: always
    hostname: dbpsql
    networks:
      - django_network
    ports:
      - "9500:5432"
    volumes:
      - /home/pasha/PycharmProjects/pythonProject/Django_tutorial/dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg4
    restart: unless-stopped
    env_file:
      - pg4.env
    ports:
      - "5550:80"
    depends_on:
      - dbpsql
    networks:
      - django_network
networks:
  django_network:
volumes:
  postgres_data:



